### ISSUE TITLE
Pipeline - VSBuild@1 does not generate a package with _content\Blazorise\*

### ISSUE THREAD

**Issue by vbray1979** [stsrki/Blazorise#1017]
Hi,

I am currently trying to setup CI using DevOps but the generated package do not contain _content\Blazorise\* data.

_pipeline yml:_

```
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

- task: VSBuild@1
  inputs:
    solution: 'src/Client/xxx.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```
However, I am getting _content\Balzorise.Bootstrap\* , _content\Balzorise.Charts\* and _content\Blazorise.Snackbar\*
Notice that publishing a package using vs2019 create all expected content data, the three listed above plus _content\Blazorise\*.

Any idea would be very much appreciated
