### ISSUE TITLE
Help: Set TableRowCell MinWidth

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [stsrki/Blazorise#1761]
Hello,
I use a TextEdit inside a TableRowCell. Is it possible to set a minimum witdth for the input (for example on small devices)?

Thanks for help :)

**Comment by stsrki** [comment]
I plan to implement utility classes in Blazorise, similar to [this](https://getbootstrap.com/docs/4.6/utilities/sizing/) but it will not be done soon.

For now, your best option is to use CSS and target `TableRowCell` class name.

```cshtml
<TableRowCell Class="your-custom-cell">
```

```css
.your-custom-cell {
  min-width: 200px;
}

@media only screen and (max-width: 600px) {
  .your-custom-cell {
    min-width: 100px;
  }
}
```
