### ISSUE TITLE
BarDropdownItem padding

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1849]
you add padding via this line
`builder.Append( $"padding-left: { 1.5d * ( ParentStore.NestedIndex + 1 ) }rem", ParentStore.IsInlineDisplay );`
but when app culture is not tr-TR it will be converted to 

```css
element.style {
    padding-left: 4,5rem;
} 
```

so the browser can not detect it

is there possible to add culture to your calculations?
