### ISSUE TITLE
[Check] Class parameter applied to inner input component

### ISSUE THREAD

**Issue by damianog** [stsrki/Blazorise#2264]
I want to apply a custom style to the Check component but the Class value is transfered to the inner input element not to container of the input an label tags and I need to customize the label.

**Comment by stsrki** [comment]
It is by design. The Class is always set to the main element. Every provider can have its own unique structure and it is impossible to determine where some custom class or style could go. Your best option is to use CSS.

```css
input[type=checkbox].custom-control-input + .custom-control-label {
    color: purple;
    font-size: 1.5rem;
}
```

**Comment by damianog** [comment]
I understand, my case a little particular I have a checklist, a check to the wrong or right checkbox change the label to red or green and set it to bold, the class value is assigned by a function that test che value.

**Comment by stsrki** [comment]
Can you post code sample I will see what can be done?

**Comment by damianog** [comment]
Here a sample,

![image](https://user-images.githubusercontent.com/2786682/116411379-f3167380-a835-11eb-8990-330cead78576.png)

the second solution runs fine for me so we can consider closed the issue.

```
@page "/test"
<h3>Checklist</h3>
<style>
    .wrong-answer label {
        font-weight: bold;
        color: red;
    }

    .good-answer label {
        font-weight: bold;
        color: green;
    }
</style>

<h4>The cleaner way</h4>
@foreach (var i in items)
{
    <Check @bind-Checked="i.Value" Class="@ClassResult(i)"> @i.Text</Check>
}


<h4>Workaraound</h4>
@foreach (var i in items)
{
    <div class="@ClassResult(i)">
        <Check @bind-Checked="i.Value"> @i.Text</Check>
    </div>
}

@code {

    class CheckItem
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public bool IsValid { get; set; }
        public bool Value { get; set; }
    }

    List<CheckItem> items = new List<CheckItem>();

    protected override void OnInitialized()
    {
        items.Add(new CheckItem { Id = 1, Text = "Answer 1", IsValid = false });
        items.Add(new CheckItem { Id = 2, Text = "Answer 2", IsValid = false });
        items.Add(new CheckItem { Id = 3, Text = "Answer 3", IsValid = true });
        items.Add(new CheckItem { Id = 4, Text = "Answer 4", IsValid = false });
    }

    string ClassResult(CheckItem item)
    {
        return item.Value ? (item.IsValid ? "good-answer" : "wrong-answer") : "";
    }

}

**Comment by stsrki** [comment]
You only need to change this

```css
<style>
    .wrong-answer + label {
        font-weight: bold;
        color: red;
    }

    .good-answer + label {
        font-weight: bold;
        color: green;
    }
</style>
```
